services:
  frontend:
    build:
      context: ./DnD-Inverntory-managment
    container_name: dnd_frontend
    ports:
      - "8080:80"
    depends_on:
      - backend

  backend:
    build:
      context: ./dnd-backend
    container_name: dnd_backend
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: production
      DB_HOST: db
      DB_USER: root
      DB_PASSWORD: example
      DB_NAME: dnd
      DB_PORT: 3306
    depends_on:
      - db

  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: dnd
    ports:
      - "3307:3306"
