name: Build and Push Docker Images

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push frontend
        run: |
          docker build -t alessdw2003/frontend:latest ./frontend
          docker push alessdw2003/frontend:latest

      - name: Build and push backend
        run: |
          docker build -t alessdw2003/backend:latest ./backend
          docker push alessdw2003/backend:latest

      - name: Trigger Portainer stack update
        run: |
          curl -X POST https://hook.bellton.synology.me/api/stacks/webhooks/api/stacks/webhooks/d55eb74f-0e40-4517-9cd4-a8823ef9f8a0


