name: Deploy to Server

on:
  push:
    branches:
      - main   # alleen bij push naar main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.8.1
        with:
          ssh-private-key: ${{ secrets.SERVER_SSH_KEY }}

      - name: Deploy to server
        run: |
          ssh -o StrictHostKeyChecking=no user@YOUR_SERVER_IP "
            cd /pad/naar/jouw/project &&
            git pull &&
            docker compose down &&
            docker compose up -d --build
          "
